### ISSUE TITLE
ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by viniciusbitt** [sirLisko/redux-persist-transform-expire-in#8] opened 2020-08-14 20:58 UTC
ReferenceError: localStorage is not defined at transformExpire

My code: 

```
import { createStore } from 'redux'
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage'
import expireIn from "redux-persist-transform-expire-in";

const persistConfig = {
    key: '@key',
    storage,
    transforms: [expireIn((1 * 60 * 60 * 1000), 'expirationKey', {})]
}

const persistedReducer = persistReducer(persistConfig, reducer);

const store = createStore(persistedReducer)
const persistor = persistStore(store);
```

**Comment by sirlisko** [comment] 2020-08-15 06:50
Hey @BetaPlays3 are you using it with SSR?
Do you have a codesandbox example?

**Comment by viniciusbitt** [comment] 2020-08-15 14:55
Store: 
```
import { createStore } from 'redux'
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage'
import expireIn from "redux-persist-transform-expire-in";

const persistConfig = {
    key: '@key',
    storage,
    transforms: [expireIn((1 * 60 * 60 * 1000), 'expirationKey', {})]
}

const persistedReducer = persistReducer(persistConfig, reducer);

const store = createStore(persistedReducer)
const persistor = persistStore(store);
```

_app.js: 
```
import { store, persistor } from '../store';
import { PersistGate } from 'redux-persist/integration/react'
<Provider store={store}>
     <PersistGate loading={null} persistor={persistor}>
                        <Component {...pageProps} />
     </PersistGate>
</Provider>
```

I believe I am not using SSR

**Comment by sirlisko** [comment] 2020-10-22 22:31
I couldn't reproduce it. Closing this.
@BetaPlays3 if you still have the problem happy to give it a better look if you have more details :)

**Closed as completed by sirlisko** 2020-10-22 22:32 UTC
